- type: job
  id: CentCommOSS
  name: job-name-centcommOSS
  description: job-description-centcommOSS
  playTimeTracker: JobCentCommOSS
  requirements:
    - !type:RoleTimeRequirement
      role: JobCentCommAssistant
      time: 36000 #10 hrs # _FNStation-Time
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 #25 hrs # _FNStation-Time
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 #15 hrs
  weight: 20
  startingGear: OSSCentCommGear
  icon: "JobIconNanotrasenAverage"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: OSSCentCommGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    backpack: ClothingBackpackERTSecurity
    belt: ClothingBeltSecurityFilled
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    pocket2: WeaponPistolMk58
  storage:
    back:
    - MagazinePistol
    - Flash
